import path from "path"
import react from "@vitejs/plugin-react"
import { defineConfig } from "vite"
import { inspectAttr } from 'kimi-plugin-inspect-react'
import sitemapPlugin from 'vite-plugin-sitemap'

// https://vite.dev/config/
export default defineConfig({
  base: '/',
  plugins: [
    inspectAttr(),
    react(),
    sitemapPlugin({
      hostname: 'https://newlvlstudio.com',
      dynamicRoutes: [
        '/services',
        '/works',
        '/studio',
        '/michael-vail',
        '/journal',
        '/packages',
        '/starter-pack',
        '/contact',
        '/privacy',
        '/terms',
        '/port-orange-website-design',
        '/daytona-beach-website-design',
        '/volusia-county-website-design',
        '/central-florida-website-design',
        '/works/the-grass-guys',
        '/works/dh-luxury-roofing',
        '/works/volusia-legal-group',
        '/works/ember-oak-coffee',
        '/works/love-handles-bbq',
        '/works/crescent-harbor',
        '/works/coastal-standard-realty',
        '/works/el-taller-2026',
        '/works/la-tequila-2026',
        '/works/the-best-landscape-2026',
        '/works/aureline-estates',
        '/works/stone-timber-remodeling',
        '/works/lotus-beauty-house',
        '/journal/website-visuals-costing-customers',
        '/journal/volusia-county-contractors-visual-content',
        '/journal/port-orange-businesses-professional-visual-content',
        '/journal/local-businesses-professional-marketing-images',
        '/journal/contractors-better-visuals-win-jobs',
        '/journal/short-form-video-future-local-marketing',
        '/journal/professional-video-production-how-it-works',
        '/journal/what-are-professional-marketing-visuals',
        '/journal/small-business-consistent-social-media-visuals',
        '/journal/best-video-content-restaurants-port-orange',
        '/journal/volusia-county-businesses-compete-better-visuals',
        '/journal/video-content-cost-breakdown',
        '/journal/florida-restaurants-social-media-professional-visuals',
        '/journal/car-dealerships-video-move-inventory-faster',
        '/journal/short-form-video-changing-small-business-marketing',
        '/journal/video-content-local-businesses-more-customers',
        '/journal/professional-images-real-estate-volusia-county',
        '/journal/modern-video-vs-traditional-production',
        '/journal/video-content-pricing-explained',
        '/journal/video-med-spas-concept-project-30-days',
        '/journal/professional-visuals-med-spas-wellness-clinics',
        '/journal/professional-images-florida-real-estate-agents',
        '/journal/5-industries-professional-ad-creative',
        '/journal/is-seo-worth-it-for-my-small-business',
        '/journal/how-long-does-it-take-to-see-results-from-seo',
        '/journal/website-first-impression',
        '/journal/five-second-website-test',
        '/journal/five-signs-website-costing-leads',
        '/journal/what-is-website-first-impression-audit',
        '/journal/local-seo-port-orange-businesses',
        '/free-seo-tools',
        '/local-visibility-insights',
        '/local-visibility-insights/website-trust',
        '/local-visibility-insights/customer-decision-path',
        '/local-visibility-insights/google-profile-completeness',
        '/local-visibility-insights/contact-information',
        '/local-visibility-insights/review-recency',
        '/local-visibility-insights/mobile-readiness',
      ],
      exclude: ['/netlify-forms'],
      generateRobotsTxt: false,
      outDir: 'dist',
    }),
  ],
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-react': ['react', 'react-dom', 'react-router-dom', 'react-router', 'react-helmet-async'],
          'vendor-motion': ['framer-motion'],
          'vendor-gsap': ['gsap', 'lenis'],
        },
      },
    },
  },
  server: {
    port: 3000,
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
